### PR TITLE
Modified helper files to download files from wasabi and updated the c…

### PR DESCRIPTION
**Pull request by Shyam-AI**
…onfig file

## Patch Description
endpoint url modified in helper.py of storage manager
(If not already mentioned in the original conversation)<br/>

## Testing Instructions
The modifications can download files from wasabi (similar to aws)

### CODE REVIEW

**Comment by jkhenning** [comment]
@Shyam-AI can you confirm my previous comment works for you?

**Comment by Shyam-AI** [comment]
Hi @jkhenning was tied up with a different work. I am unable to use wasabi with the storage manager. I might be missing out on somethimg. Could you possibly provide with an example as to how to use storage manager with wasabi? 

Thanks

**Comment by jkhenning** [comment]
Hi, As I said before:

> for wasabi and minio you should use a storage URL such as s3://<server-address>:433/... (if using a secure connection, for example)

**Comment by jkhenning** [comment]
@Shyam-AI did you get it to work with my suggested configuration?

**Comment by jkhenning** [comment]
Closing this as stale, please reopen if required.

**Pull request closed without merging**
