### PR TITLE
Fix #1348

### LINKED ISSUE #1348: Bug: PermissionError: [WinError 5] while uploading dataset
## Describe the Bug
When uploading a dataset using `clearml-data sync` on Windows, the following error intermittently occurs: `PermissionError: [WinError 5] Access is denied`.

## Investigation
The error is triggered on the following line in the code:  
https://github.com/allegroai/clearml/blob/master/clearml/binding/artifacts.py#L1141C18-L1141C19.

This issue is unstable and difficult to reproduce consistently. However, it becomes a significant problem when working with large datasets. For instance, my team faced this error while attempting to upload a dataset containing 700 000 items. The process took approximately 5 hours to compute all file hashes, only for the `WinError 5` to unexpectedly appear.

## Steps to Reproduce
The following script simulates the aforementioned line of code and demonstrates the issue:

```python
import os
from tempfile import mkstemp
from tqdm import trange, tqdm
from shutil import move

for i in trange(100000):
    fd, local_filename = mkstemp()
    os.close(fd)
    fd, temp_filename = mkstemp()
    os.close(fd)
    
    try:
        os.replace(local_filename, temp_filename)
    except PermissionError:
        tqdm.write("PermissionError")
    
    os.remove(temp_filename)
```

When running this script on multiple Windows machines, I observed about 6 `PermissionError` exceptions over 100 000 iterations.  
**Running the script as administrator does not resolve the issue.**

## Possible Solution
I suggest replacing the use of `os.replace(local_filename, temp_filename)` with `shutil.move(local_filename, temp_filename)`. Both methods achieve the same functionality, but `shutil.move` does not raise the `PermissionError` on Windows.

### PR DESCRIPTION
**Pull request by Octoslav**
## Related Issue \ discussion
Fix #1348 

`os.replace` in bundle with `mkstemp` could raise `PermissionError: [WinError 5]` on windows systems.

## Patch Description
Replaced `os.replace` with `shutils.move`.

## Other Information
See details in the issue

### CODE REVIEW

**Comment by jkhenning** [comment]
@Octoslav, since `os.replace` should be atomic in Linux, and `shutil.move` can have different behaviors (such as copying between devices), can you please make this change specific to windows only?

**Comment by Octoslav** [comment]
@jkhenning Maybe in this case it is better to just wrap `os.replace` in a `try\except` block? Like:

```python
try:
    os.replace(local_filename, temp_filename)
except PermissionError:
    os.replace(local_filename, temp_filename)  # Try again, and if it fails, throw an exception.
```


What do you think?

**Comment by jkhenning** [comment]
If that addresses the issue, I would be fine with it 🙂

**Comment by Octoslav** [comment]
Hi @jkhenning
please, check mr

**Comment by jkhenning** [comment]
Hi @Octoslav, that looks OK, I will merge it

**Pull request merged**
