### PR TITLE
Update README.md to include community roadmap

### PR DESCRIPTION
**Pull request by stelford**
Initial wild stab at community roadmap, obviously open to lots of changes :)

### CODE REVIEW

**Comment by bmartinn** [comment]
Hi @stefempath 

I think that with "release 0.18" we actually refer to the next `cleaml` python package release, assuming this is 0.17.6, correct ?

I think that "Fix reporting after task closing" is just a bug fix, not really road-map worthy, no?

**Comment by stelford** [comment]
Take #2 on the verbage and item list :)

**Comment by bmartinn** [comment]
I would push the documentation to v1.0
Also, we are adding multi-model per Task support in v1.0

**Comment by stelford** [comment]
I will need to close this one down and re-open against the Tag 1.0 :)

**Pull request closed without merging**
