### PR TITLE
Create pylint.yml

### PR DESCRIPTION
**Pull request by bai2020-05**
## Related Issue \ discussion
If this patch originated from a github issue or slack conversation, please paste a link to the original discussion<br/>

## Patch Description
Description of what does the patch do. If the patch solves a bug, explain what the bug is and how to reproduce it 
(If not already mentioned in the original conversation)<br/>

## Testing Instructions
Instructions of how to test the patch or reproduce the issue the patch is aiming to solve

### CODE REVIEW

**Comment by jkhenning** [comment]
@bai2020-05 can you please provide some context for this PR?

**Comment by jkhenning** [comment]
@bai2020-05 , I think that since we internally use Flake8, we should start with it - WDYT?

**Comment by john-zielke-snkeos** [comment]
Yes, Flake8 is definitely a good idea, but does it provide auto-formatting as well? I have used Flake8 for the linting, but not for the code formatting, but if it provides that as well, it would be enough

**Comment by jkhenning** [comment]
@bai2020-05 is this still relevant?

**Comment by john-zielke-snkeos** [comment]
I am not sure it is relevant for the author, but it is still relevant in general IMO

**Comment by jkhenning** [comment]
@john-zielke-snkeos Since we use Flake8 internally (btw I think its much more common for open source projects), I think we should have a new PR using it, WDYT?

**Comment by john-zielke-snkeos** [comment]
Yes, it probably makes sense if you just add your config/setup for this to the repo so other contributors can easily use that.

**Pull request closed without merging**
